apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: devops-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      myapplication: myapp
  template:
    metadata:
      labels:
        myapplication: myapp
    spec:
      containers:
      - name: myapp
        image: app:0
        ports:
        - containerPort: 1234
        volumeMounts:
        - name: app-logs
          mountPath: /home/application/brain-tuck/logs
        env:
        - name: MONGO_URL
          value: brain-tuck
      nodeName: mas    
      volumes:
      - name: app-logs
        hostPath:
          path: /home/nader/app
