apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: devops-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: app:47
          ports:
            - containerPort: 1234
          volumeMounts:
            - name: data-logs
              mountPath: /home/application/brain-tuck/logs
      nodeName: mas
      volumes:
         - name: data-logs
           hostPath:
              path: /home/nader/app
            
 
