apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: devops-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: app:1
          ports:
            - containerPort: 1234
          volumeMounts:
            - name: data-logs
              mountPath: /home/application/brain-tuck/logs
      nodeName: master
      volumes:
         - name: data-logs
           hostPath:
              path: /home/nader/app
